### ISSUE TITLE
Exports not happening

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#153]
We are not able to export CSVs or JSONs.  The console log shows a websocket connection error.

### Expected behavior:

- Filter list of items to export
- Select All (optional -> All results that match this search)
- Choose an export type (CSV or JSON)
- File compiles and Notifications in the menu displays a red icon
- Navigate to Notifications and download file 

### Actual behavior
- Filter list of items to export
- Select All (optional -> All results that match this search)
- Choose an export type (CSV or JSON)
- Nothing happens. Console shows multiple errors listed as `action_cable.js:241 WebSocket connection to 'wss://geomg.lib.umn.edu/cable' failed: `

@mberkowski Do you know if this is a server configuration issue? I am not sure when exports stopped working. I believe that it was functional when Eric pushed the enhancement last month.

**Comment by mberkowski** [comment]
@karenmajewicz Last communications I had with EL, ActionCable was not yet working properly. "It's not a show stopper that AC isn't working there, it just means you don't know your export file is ready unless you refresh the page" 

2 things going on:
1) as EL noted, the ActionCable integration doesn't yet work so you need to refresh to see the notifications light up.
2) The Sidekiq service which does background job processing on these exports was not running. This has probably been since a server patch & reboot about a week and a half ago. I will figure out why this happened, but it's not the application's fault.

Right now it lists 5 CSVs for download, some of which were probably me.

**Comment by karenmajewicz** [comment]
Thank you! I had forgotten the refresh part!  

I know that our RA tried to do some exports last week that never showed up. Maybe the Sidekiq service was the problem.

**Comment by karenmajewicz** [comment]
I am seeing this same behavior on geomg prod today. I can only export 1 page of records at a time.

**Comment by karenmajewicz** [comment]
#179 is a better descriptor of the current issue.
