### ISSUE TITLE
Add collection reports and stats

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#81]
We include a number of collection statistics in our weekly, monthly, and bi-annual reports. [I have been using Airtable to tally these numbers](https://airtable.com/shrfjT0MmfDuEX1a8/tblYB397ozv6kAMhu), but it's not going to work as a long term solution. Could something like this be added to GEOMG? Maybe a new page called "Reports"? Or maybe this could be a "Dashboard" type view that also serves as the main/home page for the app?

Here are some stats we report on:
- total number of records 
- total number of sources we are pulling from
- collections per institutional contributors
- published items per collection
- how many records were added/removed in a given time period (using Date Accessioned and Date Retired) per collection
- growth of total number of records over time

**Comment by ewlarson** [comment]
Yes, we can add a "Dashboard" to the GEOMG project.

For flexibility, I'd lean towards adding a simple BI tool, allowing you to add/edit the dashboard, rather than hard-coding a few reports and charts. One of the developers behind [Instacart](https://www.instacart.com/) has released a bunch of their code as open source. Perhaps their [Blazer](https://github.com/ankane/blazer) project would work for us here?

Our biggest hurdle will be that our data is largely JSON, which will make reporting slower and querying a little uglier.

**Comment by ewlarson** [comment]
Will take quick stab at this via rails tooling.

**Comment by karenmajewicz** [comment]
- total number of records 
- published items per collection
- how many records were added/removed in a given time period (using Date Accessioned and Date Retired) per collection
- growth of total number of records over time

**Comment by karenmajewicz** [comment]
The current Blazer plugin is sufficient for this purpose.
